# Generated by Django 6.1 on 2026-08-17 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RotaAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.PositiveSmallIntegerField()),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('machinist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rota_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'slot'],
                'constraints': [models.UniqueConstraint(fields=('date', 'slot'), name='unique_rota_slot')],
            },
        ),
    ]
