# Generated by Django 6.1 on 2026-08-17 15:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('initials', models.CharField(max_length=4, unique=True)),
                ('is_engineer', models.BooleanField(default=False)),
                ('is_machinist', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['initials'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(editable=False, max_length=24, unique=True)),
                ('job_label', models.CharField(blank=True, max_length=240)),
                ('job_name', models.CharField(max_length=200, verbose_name='Part number')),
                ('project', models.CharField(max_length=200)),
                ('part_version', models.CharField(max_length=50)),
                ('submitted_date', models.DateField(default=django.utils.timezone.localdate)),
                ('priority', models.IntegerField(choices=[(0, 'Urgent'), (1, 'High'), (2, 'Medium'), (3, 'Low')], default=2)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('deadline', models.DateField()),
                ('destination', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('folder_path', models.CharField(max_length=500)),
                ('pdf_filename', models.CharField(max_length=260)),
                ('dxf_filename', models.CharField(max_length=260)),
                ('vcarve_filename', models.CharField(max_length=260)),
                ('pdf_stamp', models.CharField(blank=True, max_length=80)),
                ('dxf_stamp', models.CharField(blank=True, max_length=80)),
                ('vcarve_stamp', models.CharField(blank=True, max_length=80)),
                ('files_confirmed', models.BooleanField(default=False)),
                ('duplicate_acknowledged', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('on_hold', 'On hold — no material'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('materials_present', models.BooleanField(default=False)),
                ('cancel_reason', models.TextField(blank=True)),
                ('overdue_reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('panel_used', models.CharField(blank=True, max_length=120)),
                ('machinist_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.panel')),
                ('machinist_primary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_jobs', to='jobs.person')),
                ('machinist_secondary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_jobs', to='jobs.person')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_jobs', to='jobs.person')),
            ],
            options={
                'ordering': ['priority', 'deadline', 'created_at'],
            },
        ),
    ]
