# Generated by Django 6.1 on 2026-08-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='dxf_filename',
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.AlterField(
            model_name='job',
            name='folder_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='pdf_filename',
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.AlterField(
            model_name='job',
            name='vcarve_filename',
            field=models.CharField(blank=True, max_length=260),
        ),
    ]
